title: Hello, guys! I'm Denys
description: > # this means to ignore newlines until "baseurl:"
  This just a personal blog of a person who is always mad about Quality, Security, Automation and AI.
  Quiality Management, Assurance, Control, Testing/Processes Automation.
  DevOps, AIOps, LLMS, Workflows automation.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Just Denys # add your name
author-img: darkusha2.jpg # add your photo
about-author: I am a person who always mad about Quality, Security, Automation and AI. # add description
social-twitter: nogyvnyz # add your Twitter handle
social-linkedin: ma3xdedu111ka # add your Linkedin handle
social-github: 1v1a3x # add your Github handle
social-email: ma3xdedu111ka@gmail.com # add your Email address
# social-facebook: # add your Facebook handle
social-instagram: arkusha.fm # add your Facebook handle

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
